# BIR PROFILI QA ISMI ILE AKTIFLESTIRIRDIKTEN SONRA ARTIK BU DOSYA KULLANILACAKTIR
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

# ACCOUNT, PREFIX OLARAK KULLANILIYOR
accounts:
  message: "Welcome the bank application accounts related QA APIs"
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smith@mail.com"
  onCallSupport:
    - (555) 555-2010
    - (555) 555-2011