# NAME SAYESINDE BU MICROSERVICE, CONFIGSERVER ICERISINDE TANIMLI YML DOSYALARINA VE ILGILI PROFILLERE ERISIR
# CONFIG ICERISINDE CONFIGSERVER ILE MICROSERVICE VE CONFIGSERVICE ARASINDAKI BAGLANTI SAGLANIR - BURADA KULLANILAN CONFIGSERVER ILE PROJE OLARAK KULLANILAN CONFIGSERVER ISMI HER ZAMAN AYNI OLMAYABILIR, BURADA AYARLAMA YAPARKEN CONFIGSERVER KULLANILIR
# OPTIONAL ISE CONFIGSERVER'A BAGLANAMAMA DURUMUNDA DA ACCOUNTS MS'IN YINE DE CALISMASINI ISTEDIGIMIZI GOSTERMEK ICIN KULLANILIR
server:
  port: 8000
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

# * ILE SPRING BOOT ACTUATOR TARAFINDAN DESTEKLENEN TUM MANAGEMENT ENDPOINTLERI KULLANIMA ACILIR
# BU ENDPOINTLER ICERISINDE REFRESH ILE ILGILI OLAN ENDPOINT DE BULUNUR
management:
  endpoints:
    web:
      exposure:
        include: "*"