services:
# BU DOSYA DOCKER COMPOSE UP KOMUTU ILE CALISTIRILDIGINDA, BURADAKI TANIMLANAN CONTAINER SIRASINA GORE
# CONTAINER'LAR OLUSTURULACAK YANI ONCE CONFIGSERVER SONRA ACCOUNTS SEKLINDE. ANCAK VARSAYILAN OLARAK CONFIGSERVER
# TAM OLARAK CALISIR DURUMA GELMEDEN DIGER CONTAINER INIT EDILIR, BU DURUM PROBLEM CIKARABILIR
# ACCOUNTS'UN CONFIGSERVER'DAN ONCE CALISMASINI TAMAMLAMASI DEMEK CONFIGSERVER'DAN GEREKEN CONFIG BILGILERINI ALAMADAN BASLAMASI DEMEKTIR
# HEALTHCHECK - TEST ICERISINDE VERILEN LINKTEN GELEN CEVABI 10S SONRA AL, EGER HATA OLUSURSA 10 DEFA DENE, HER BIR DENEME ARASI 10S, LINKE ISTEK YAPILDIKTAN SONRA BEKLEME SURESI 5S
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 5s
      retries: 10
      timeout: 5s
      interval: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "serdarkorkmaz/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "serdarkorkmaz/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8000:8000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
# IKINCI TARAFTA KULLANILAN CONFIGSERVER ISMI YUKARDA TANIMLANAN CONTAINER'I REFERE EDER
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "serdarkorkmaz/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "serdarkorkmaz/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  serdar:
    driver: "bridge"
